---
micronaut:
  application:
    name: genericmicronautcruds

---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/medical?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 992200